resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/28.yaml

packages:
  - .

extra-deps:
  - github: adiR28/beam
    commit: 2f9a4b45bc43caab717eff94c0974ca4fd71445e
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
      - beam-sqlite
  - flatparse-0.5.1.0@sha256:6f5bc2d750061eac198dae1ca700d8c5c9d69dc8a536d53fdccd21a115ccb9aa,4537
