resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/28.yaml

packages:
  - .

extra-deps:
  - github: mycodedstuff/beam
    commit: 26eebb4ad6178222848f67441d416df261f012d8
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
      - beam-sqlite
  - github: AndrasKovacs/flatparse
    commit: 7ec336cd75bc2e66b089d27a87a5490c08ce9446
