name: Haskell CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7']
        os: [ubuntu-latest, macOS-latest]
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - if: matrix.os == 'macOS-latest'
        run: |
          brew install llvm@12
          brew link llvm@12

      - name: Set up PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v6
        id: postgres
        with:
          database: testdb

      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - name: Configure stack
        run: |
          stack config set system-ghc --global true
          stack config set install-ghc --global false

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}

      - name: Build dependencies
        run: stack build --only-dependencies

      - name: Build
        run: stack build
